### ISSUE TITLE
Creates blank space under bags that are currently worn

### ISSUE THREAD

**Issue by Aeded** [LudiusMaximus/SellPricePerUnit#1]
![image](https://user-images.githubusercontent.com/45561230/66662017-50dd6d80-ec48-11e9-8538-1bea6d244920.png)

**Comment by LudiusMaximus** [comment]
Thanks. I will look into this! But it will take some weeks as I am pretty busy at the moment.

**Comment by LudiusMaximus** [comment]
Fixed with version 1.4.
Thanks again for reporting it.
